import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

// Primary configuration using environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

// Fallback configuration
const FALLBACK_SUPABASE_URL = "https://byetrxydzttvxnsquuac.supabase.co"
const FALLBACK_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZXRyeHlkenR0dnhuc3F1dWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTEzMjIsImV4cCI6MjA2MzY4NzMyMn0.sdppDVah1kGSn80cBYtAscqMTPf9ngfxiWNKElPjg5w"

// Use environment variables if available, otherwise use fallback
const finalUrl = supabaseUrl || FALLBACK_SUPABASE_URL
const finalKey = supabaseAnonKey || FALLBACK_SUPABASE_ANON_KEY

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
})

// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://byetrxydzttvxnsquuac.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZXRyeHlkenR0dnhuc3F1dWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTEzMjIsImV4cCI6MjA2MzY4NzMyMn0.sdppDVah1kGSn80cBYtAscqMTPf9ngfxiWNKElPjg5w";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });
